/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel.GUI.ServiceGUI;

import Hotel.BLL.HotelError;
import Hotel.BLL.ServiceBLL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yue
 */
public class ServiceForm extends javax.swing.JPanel {

    /**
     * Creates new form ServiceForm
     */
    ServiceBLL service = new ServiceBLL();

    public ServiceForm() {
        initComponents();
        service.initServiceList((DefaultTableModel) tblService.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ServiceSubForm = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lableNeam = new javax.swing.JLabel();
        txtTenDichvu = new javax.swing.JTextField();
        txtDonviTinh = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnFgoback = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        chanBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTxT = new javax.swing.JTextField();

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lableNeam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableNeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableNeam.setText("YO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel2.add(lableNeam, gridBagConstraints);

        txtTenDichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDichvuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 0, 49);
        jPanel2.add(txtTenDichvu, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 0, 49);
        jPanel2.add(txtDonviTinh, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 0, 49);
        jPanel2.add(txtDongia, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Đơn Giá :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tên Dịch Vụ :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Đơn Vị Tính : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        jPanel2.add(jLabel6, gridBagConstraints);

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel2.add(btnSave, gridBagConstraints);

        btnFgoback.setText("Trở lại");
        btnFgoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFgobackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel2.add(btnFgoback, gridBagConstraints);

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel2.add(btnRefresh, gridBagConstraints);

        jPanel3.add(jPanel2);

        ServiceSubForm.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout(0, 10));

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Đơn Vị Tính", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblService);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        addBtn.setText("Thêm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel8.add(addBtn);

        chanBtn.setText("Sửa ");
        chanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanBtnActionPerformed(evt);
            }
        });
        jPanel8.add(chanBtn);

        delBtn.setText("Xóa");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel8.add(delBtn);

        jPanel7.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Tìm kiếm ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jLabel1, gridBagConstraints);

        searchTxT.setText("Nhập thông tin tìm kiếm");
        searchTxT.setPreferredSize(new java.awt.Dimension(115, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel9.add(searchTxT, gridBagConstraints);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel7, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
 int bien = 0;  //bien = 1 thi la them  , = 2 thi la sua
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        lableNeam.setText("Chào mừng bạn đến với thêm dịch vụ");
        bien = 1;
        txtTenDichvu.setText("");
        txtDonviTinh.setText("");
        txtDongia.setText("");
        ServiceSubForm.setSize(500, 400);
        ServiceSubForm.setVisible(true);
        System.out.println(bien);
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        if (tblService.getSelectedRow() == -1) {
            JOptionPane.showConfirmDialog(null, "  Ơ ?! ", "A WISE MAN ONCE SAID : ", JOptionPane.YES_OPTION);
        } else {
            int UwU = JOptionPane.showConfirmDialog(null, "Có chắc xóa ko ", "I'm Amẻica", JOptionPane.YES_NO_OPTION);
            if (UwU == 0) {

                int O = JOptionPane.showConfirmDialog(null, "Chắc thật ko ?", "?!", JOptionPane.YES_OPTION);
                if (O == 0) {
                    int U = JOptionPane.showConfirmDialog(null, "Xóa rồi ko làm lại đc đâu ?", "FBI WARNING !!!", JOptionPane.YES_OPTION);
                    if (U == 0) {
                        service.DeleteService(tblService.getValueAt(tblService.getSelectedRow(), 0).toString());
                        service.initServiceList((DefaultTableModel) tblService.getModel());
                    }
                }
            }

        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void txtTenDichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDichvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDichvuActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (bien == 1) { //them
                if (txtDongia.getText().isEmpty() || txtTenDichvu.getText().isEmpty() || txtDonviTinh.getText().isEmpty()) {
                    throw new HotelError(HotelError.ErrorCode.INVALID_TEXT);
                } else {
                    service.AddService(txtTenDichvu.getText(), txtDonviTinh.getText(), txtDongia.getText());
                    service.initServiceList((DefaultTableModel) tblService.getModel());
                    ServiceSubForm.setVisible(false);
                }
            } else if (bien == 2) { // sua
                int x = JOptionPane.showConfirmDialog(null, " Có chắc bạn muốn sửa như thê này ko ?! ", "A great man one said : ", JOptionPane.YES_NO_OPTION);
                if (x == 0) {
                    if (txtDongia.getText().isEmpty() || txtTenDichvu.getText().isEmpty() || txtDonviTinh.getText().isEmpty()) {
                        throw new HotelError(HotelError.ErrorCode.INVALID_TEXT);
                    } else {
                        service.UpdateService(tblService.getValueAt(tblService.getSelectedRow(), 0).toString(),
                                txtTenDichvu.getText(),
                                txtDonviTinh.getText(),
                                txtDongia.getText());
                        service.initServiceList((DefaultTableModel) tblService.getModel());
                        ServiceSubForm.setVisible(false);
                    }
                }
            }
        } catch (Exception e) {
            System.err.print(e);
        } catch (HotelError ex) {
            Logger.getLogger(ServiceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanBtnActionPerformed
        if (tblService.getSelectedRow() == -1) {
            // System.out.println("Chua chon dich vu de ma sua");
            JOptionPane.showConfirmDialog(null, " Ơ ?! ", "A wise man one said : ", JOptionPane.YES_OPTION);
        } else {
            lableNeam.setText("Chào mừng bạn đến với sửa dịch vụ ");
            bien = 2;
            txtTenDichvu.setText(tblService.getValueAt(tblService.getSelectedRow(), 1).toString());
            txtDonviTinh.setText(tblService.getValueAt(tblService.getSelectedRow(), 2).toString());
            txtDongia.setText(tblService.getValueAt(tblService.getSelectedRow(), 3).toString());
            ServiceSubForm.setSize(500, 400);

            ServiceSubForm.setVisible(true);// TODO add your handling code here:
            System.out.println(bien);
        }
    }//GEN-LAST:event_chanBtnActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Có chắc làm mới ko ? ", "?!", JOptionPane.YES_OPTION);
        if (x == 0) {
            txtTenDichvu.setText("");
            txtDonviTinh.setText("");
            txtDongia.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnFgobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFgobackActionPerformed
        ServiceSubForm.setVisible(false);
    }//GEN-LAST:event_btnFgobackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ServiceSubForm;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnFgoback;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton chanBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableNeam;
    private javax.swing.JTextField searchTxT;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtDonviTinh;
    private javax.swing.JTextField txtTenDichvu;
    // End of variables declaration//GEN-END:variables
}
